# Generated by Django 6.0.1 on 2026-01-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movie",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="movie",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="ID фильма по внешнему API (TMDB)",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="posters/"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["title"], name="movies_movi_title_652549_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["year"], name="movies_movi_year_82d175_idx"),
        ),
    ]
